--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/NaviCompassV2
branches:
  - master
projects:
  NaviCompassV2:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
...
