---
name: NaviCompass
author: Xenophilicy
version: 2.3.3
main: Xenophilicy\NaviCompass\NaviCompass
api:
- 3.0.0
mcpe-protocol:
- 407
- 408
- 428
- 431
- 440
- 448
description: View all your servers or worlds in a list using FormAPI!
commands:
  navicompass:
    description: Get info on NaviCompass
    permission: navicompass.info
permissions:
  navicompass.info:
    default: true
...
